# Generated by Django 4.0 on 2022-01-12 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0006_rename_ate_added_shippingaddress_date_added"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="razorpay_order",
            field=models.JSONField(null=True),
        ),
    ]
