# Generated by Django 4.0 on 2022-07-27 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_remove_shippingaddress_order_order_shipping_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='transaction_id',
        ),
    ]
